#!/usr/bin/env python3
# mp3_to_mp4.py
# Create MP4 video from audio with static background image for YouTube upload
# Supports: .mp3, .m4a, .wav, .aac, .flac, etc.
# Usage: python mp3_to_mp4.py input.mp3 [--bg image.jpg]

import argparse
import os
import subprocess
import sys

# Default background image (prefer .jpg, fallback to .png)
_BG_DIR = "assets/background"
DEFAULT_BG = (
    os.path.join(_BG_DIR, "background.jpg")
    if os.path.exists(os.path.join(_BG_DIR, "background.jpg"))
    else os.path.join(_BG_DIR, "background.png")
)

# CLI Help
if "-?" in sys.argv:
    print(f"Usage: python {sys.argv[0]} <audio_file_or_folder> [--bg image.jpg]")
    print("\nCreate MP4 video from audio with static background image for YouTube")
    print("Supports: .mp3, .m4a, .wav, .aac, .flac, .ogg, .opus")
    print("\nArguments:")
    print("  input                  Audio file OR folder (batch mode)")
    print("\nOptions:")
    print(f"  --bg, -b FILE          Background image (Default: {DEFAULT_BG})")
    print("  --resolution RES       Output resolution (Default: 1920x1080)")
    print("  --bitrate BR           Audio bitrate (Default: 192k)")
    print("  --no-meta              Skip embedding default ClawBible metadata")
    print("\nOutput: Auto-generated by replacing audio extension with .mp4")
    print("\nExamples:")
    print(f"  python {sys.argv[0]} output/devotion.mp3           # Single file")
    print(f"  python {sys.argv[0]} output/audio/                 # Batch folder")
    print(f"  python {sys.argv[0]} output/audio/ -o output/mp4/  # Custom output dir")
    print(f"  python {sys.argv[0]} audio.m4a --bg ~/banner.jpg   # Custom background")
    sys.exit(0)

def check_ffmpeg():
    """Check if ffmpeg is installed."""
    try:
        result = subprocess.run(["ffmpeg", "-version"], capture_output=True, text=True)
        return result.returncode == 0
    except FileNotFoundError:
        return False

def generate_output_filename(input_mp3: str, output: str = None) -> str:
    """Generate output MP4 filename from input MP3."""
    if output:
        return output
    # Replace .mp3 with .mp4
    base = os.path.splitext(input_mp3)[0]
    return f"{base}.mp4"

def create_mp4(input_mp3: str, bg_image: str, output_mp4: str, 
               resolution: str = "1920x1080", audio_bitrate: str = "192k",
               metadata: dict = None) -> bool:
    """
    Create MP4 video from MP3 audio with static background image.
    
    Args:
        input_mp3: Path to input audio file
        bg_image: Path to background image file
        output_mp4: Path to output MP4 video file
        resolution: Output video resolution (default: 1920x1080)
        audio_bitrate: Audio bitrate (default: 192k)
        metadata: Dict of ffmpeg metadata tags to embed (default: None)
    
    Returns:
        True if successful, False otherwise
    """
    # Parse resolution
    width, height = resolution.split("x")
    
    # Build ffmpeg command
    # -loop 1: Loop the image
    # -c:v libx264: Use H.264 codec
    # -tune stillimage: Optimize for still image input
    # -vf: Scale and pad to exact resolution, maintaining aspect ratio
    # -c:a aac: Use AAC audio codec
    # -pix_fmt yuv420p: Pixel format for maximum compatibility
    # -shortest: End when the shortest input ends (audio)
    
    scale_filter = f"scale={width}:{height}:force_original_aspect_ratio=decrease,pad={width}:{height}:(ow-iw)/2:(oh-ih)/2"
    
    cmd = [
        "ffmpeg",
        "-loop", "1",
        "-i", bg_image,
        "-i", input_mp3,
        "-c:v", "libx264",
        "-tune", "stillimage",
        "-vf", scale_filter,
        "-c:a", "aac",
        "-b:a", audio_bitrate,
        "-pix_fmt", "yuv420p",
        "-shortest",
    ]

    # Add metadata if provided
    if metadata:
        for key, value in metadata.items():
            cmd.extend(["-metadata", f"{key}={value}"])

    cmd.extend(["-y", output_mp4])  # Overwrite output file if exists
    
    print(f"🎬 Creating MP4 video...")
    print(f"   Input audio: {input_mp3}")
    print(f"   Background:  {bg_image}")
    print(f"   Output:      {output_mp4}")
    print(f"   Resolution:  {resolution}")
    if metadata:
        print(f"   Metadata:    {', '.join(f'{k}={v}' for k, v in metadata.items())}")
    
    try:
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode == 0:
            # Get file size
            size_mb = os.path.getsize(output_mp4) / (1024 * 1024)
            print(f"✅ Success! Created: {output_mp4} ({size_mb:.1f} MB)")
            return True
        else:
            print(f"❌ FFmpeg error:\n{result.stderr}")
            return False
    except Exception as e:
        print(f"❌ Error: {e}")
        return False


# Default metadata for ClawBible YouTube uploads
DEFAULT_METADATA = {
    "artist": "ClawBible · VI AI Foundation",
    "album_artist": "Michael Huo",
    "copyright": "© 2025-2026 VI AI Foundation · 501(c)(3)",
    "comment": "clawbible.us | michael@vi.team | VI AI Foundation",
    "url": "https://clawbible.us",
}

AUDIO_EXTENSIONS = {".mp3", ".m4a", ".wav", ".aac", ".flac", ".ogg", ".opus"}


def resolve_bg_image(bg_arg: str) -> str:
    """Resolve background image path, trying relative to CWD then script dir."""
    if os.path.exists(bg_arg):
        return bg_arg
    script_dir = os.path.dirname(os.path.abspath(__file__))
    alt = os.path.join(script_dir, bg_arg)
    if os.path.exists(alt):
        return alt
    return None


def batch_convert(folder: str, bg_image: str, resolution: str, bitrate: str,
                  metadata: dict, output_dir: str = None) -> tuple[int, int]:
    """
    Convert all audio files in a folder to MP4 videos.

    Returns:
        Tuple of (success_count, fail_count)
    """
    audio_files = sorted(
        f for f in os.listdir(folder)
        if os.path.splitext(f)[1].lower() in AUDIO_EXTENSIONS
    )

    if not audio_files:
        print(f"❌ No audio files found in: {folder}")
        print(f"   Supported: {', '.join(sorted(AUDIO_EXTENSIONS))}")
        return 0, 0

    out_dir = output_dir or folder
    os.makedirs(out_dir, exist_ok=True)

    print(f"\n📂 Batch converting {len(audio_files)} file(s) from: {folder}")
    print(f"   Output dir: {out_dir}\n")

    ok, fail = 0, 0
    for i, fname in enumerate(audio_files, 1):
        print(f"── [{i}/{len(audio_files)}] {fname}")
        input_path = os.path.join(folder, fname)
        base = os.path.splitext(fname)[0]
        output_path = os.path.join(out_dir, f"{base}.mp4")

        # Add track-specific metadata
        track_meta = {**metadata, "title": base.replace("_", " ").replace("-", " ")}

        success = create_mp4(
            input_mp3=input_path,
            bg_image=bg_image,
            output_mp4=output_path,
            resolution=resolution,
            audio_bitrate=bitrate,
            metadata=track_meta,
        )
        if success:
            ok += 1
        else:
            fail += 1
        print()

    print(f"\n{'='*50}")
    print(f"📊 Batch complete: {ok} succeeded, {fail} failed out of {len(audio_files)}")
    return ok, fail


def main():
    parser = argparse.ArgumentParser(
        description="Create MP4 video from audio with static background image for YouTube"
    )
    parser.add_argument("input", type=str,
                        help="Input audio file OR folder for batch mode")
    parser.add_argument("--bg", "-b", type=str, default=DEFAULT_BG, 
                        help=f"Background image (Default: {DEFAULT_BG})")
    parser.add_argument("--output", "-o", type=str, default=None,
                        help="Output MP4 file or directory (Default: auto)")
    parser.add_argument("--resolution", "-r", type=str, default="1920x1080",
                        help="Output resolution (Default: 1920x1080)")
    parser.add_argument("--bitrate", type=str, default="192k",
                        help="Audio bitrate (Default: 192k)")
    parser.add_argument("--no-meta", action="store_true",
                        help="Skip embedding default ClawBible metadata")
    
    args = parser.parse_args()
    
    # Check ffmpeg
    if not check_ffmpeg():
        print("❌ FFmpeg not found. Please install ffmpeg:")
        print("   macOS:  brew install ffmpeg")
        print("   Linux:  sudo apt install ffmpeg")
        sys.exit(1)
    
    # Resolve background image
    bg_path = resolve_bg_image(args.bg)
    if not bg_path:
        print(f"❌ Background image not found: {args.bg}")
        print(f"   Create: mkdir -p assets/background && cp your_image.jpg {DEFAULT_BG}")
        sys.exit(1)

    metadata = {} if args.no_meta else DEFAULT_METADATA.copy()

    # --- Batch mode (input is a directory) ---
    if os.path.isdir(args.input):
        ok, fail = batch_convert(
            folder=args.input,
            bg_image=bg_path,
            resolution=args.resolution,
            bitrate=args.bitrate,
            metadata=metadata,
            output_dir=args.output,
        )
        sys.exit(0 if fail == 0 else 1)

    # --- Single file mode ---
    if not os.path.exists(args.input):
        print(f"❌ Input file not found: {args.input}")
        sys.exit(1)
    
    # Generate output filename
    output_mp4 = generate_output_filename(args.input, args.output)

    # Add title metadata from filename
    base = os.path.splitext(os.path.basename(args.input))[0]
    metadata["title"] = base.replace("_", " ").replace("-", " ")
    
    # Create MP4
    success = create_mp4(
        input_mp3=args.input,
        bg_image=bg_path,
        output_mp4=output_mp4,
        resolution=args.resolution,
        audio_bitrate=args.bitrate,
        metadata=metadata,
    )
    
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
