#!/usr/bin/env python3
"""
Generate Chronological 6-Month reading plan audio + video (半年歷史時序聆聽 + 半年智慧讚美聆聽).

Two paired 186-day plans, per day generates:
  1. 半年歷史時序聆聽第N天-{chapters}.mp3 + .mp4
  2. 半年智慧讚美聆聽第N天-{psalms+proverbs}.mp3 + .mp4

Input is a day number (1–186) or a range (e.g. 1-5, 16-17).
Defaults: 1.5x speed, rotate voices, background music, MP4 enabled.
Day 76 is the Ps 119 special day (Ps 119 + Prov 1 + Prov 31, no Ps+Prov bonus).

Usage:
  python scripts/qt.py 1              # Day 1: 2 MP3s + 2 MP4s
  python scripts/qt.py 1-7            # Days 1-7
  python scripts/qt.py 1 --no-mp4     # MP3 only, skip MP4
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from plan_utils import (
    BOOK_CHINESE,
    BOOK_CHINESE_TW,
    BOOK_FILENAME_ABBR,
    BOOK_FILENAME_ABBR_ZH_TW,
    chapters_to_chinese,
    chapters_to_english,
    chapters_to_filename,
    load_plan,
)

PLAN_ID = "chronological-6month"
PSPROV_PLAN_ID = "psalms-proverbs-186days"

# ── Metadata ──────────────────────────────────────────────────────────────
ARTIST = "聽 Ting · VI AI for Good Foundation"
ALBUM_CHRONO = "半年歷史時序聆聽 — Chronological Bible in 6 Months"
ALBUM_PSPROV = "半年智慧讚美聆聽 — Psalms & Proverbs in 6 Months"
COPYRIGHT = "© 2025-2026 VI AI for Good Foundation · 501(c)(3) · viaiforgood.org"
COMMENT = (
    "Audio: Everest Audio Bible (Traditional Chinese, CUV) · "
    "Music: Background music from assets/bgm · "
    "Generated by Ting (github.com/viaifoundation/ting) · "
    "VI AI for Good Foundation · viaiforgood.org · bibleweb.app"
)
URL = "https://bibleweb.app"
GENRE = "Bible / Audiobook"
LANGUAGE = "zh"


def parse_day_range(spec: str) -> list[int]:
    spec = spec.strip()
    if "-" in spec:
        parts = spec.split("-", 1)
        try:
            start, end = int(parts[0]), int(parts[1])
        except ValueError:
            raise ValueError(f"Invalid day range: '{spec}'. Expected N or N-M")
        if start > end:
            raise ValueError(f"Start day {start} must be <= end day {end}")
        return list(range(start, end + 1))
    try:
        return [int(spec)]
    except ValueError:
        raise ValueError(f"Invalid day: '{spec}'. Expected an integer or range N-M")


def get_background_image() -> str | None:
    """Find the default background image, preferring .jpg then .png."""
    bg_dir = REPO_ROOT / "assets" / "background"
    for ext in (".jpg", ".jpeg", ".png"):
        candidate = bg_dir / f"background{ext}"
        if candidate.exists():
            return str(candidate)
    return None


def create_mp4(
    mp3_path: str,
    mp4_path: str,
    bg_image: str,
    title: str,
    album: str,
    track_num: int | None = None,
    total_tracks: int = 186,
) -> bool:
    """Create an MP4 video from audio + static background image with rich metadata."""
    cmd = [
        "ffmpeg",
        "-loop", "1",
        "-i", bg_image,
        "-i", mp3_path,
        "-c:v", "libx264",
        "-tune", "stillimage",
        "-vf", "scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2",
        "-c:a", "aac",
        "-b:a", "192k",
        "-pix_fmt", "yuv420p",
        "-shortest",
        # ── Metadata ──
        "-metadata", f"title={title}",
        "-metadata", f"artist={ARTIST}",
        "-metadata", f"album={album}",
        "-metadata", f"album_artist={ARTIST}",
        "-metadata", f"copyright={COPYRIGHT}",
        "-metadata", f"comment={COMMENT}",
        "-metadata", f"genre={GENRE}",
        "-metadata", f"language={LANGUAGE}",
        "-metadata", f"url={URL}",
        "-metadata", f"publisher={ARTIST}",
        "-metadata", "encoding_tool=Ting (github.com/viaifoundation/ting)",
    ]
    if track_num is not None:
        cmd.extend(["-metadata", f"track={track_num}/{total_tracks}"])

    cmd.extend(["-y", mp4_path])

    print(f"🎬 Creating MP4: {Path(mp4_path).name}")
    try:
        subprocess.run(["ffmpeg", "-version"], capture_output=True, check=True)
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode == 0:
            print(f"✅ MP4 created!")
            return True
        else:
            print(f"❌ FFmpeg error:\n{result.stderr[-500:]}")
            return False
    except FileNotFoundError:
        print("❌ FFmpeg not found. Install with: brew install ffmpeg")
        return False
    except Exception as e:
        print(f"❌ Error creating MP4: {e}")
        return False


def main() -> int:
    parser = argparse.ArgumentParser(description="半年歷史時序聆聽 + 半年智慧讚美聆聽 (186-day paired plans)")
    parser.add_argument("days", type=str, help="Day number (1–186) or range (e.g. 1-5)")
    parser.add_argument(
        "--mp4", action="store_true",
        help="Enable MP4 video generation (disabled by default)",
    )
    args = parser.parse_args()
    generate_mp4 = args.mp4

    try:
        requested_days = parse_day_range(args.days)
    except ValueError as e:
        print(f"❌ {e}")
        return 1

    # Load both plans
    chrono_path = REPO_ROOT / "assets" / "bible" / "plans" / f"{PLAN_ID}.json"
    psprov_path = REPO_ROOT / "assets" / "bible" / "plans" / f"{PSPROV_PLAN_ID}.json"

    if not chrono_path.exists():
        print(f"❌ Plan not found: {chrono_path}. Run generate_6mo_plan.py first.")
        return 1
    if not psprov_path.exists():
        print(f"❌ Plan not found: {psprov_path}. Run generate_6mo_plan.py first.")
        return 1

    chrono_plan = load_plan(chrono_path)
    psprov_plan = load_plan(psprov_path)
    max_day = chrono_plan["days"]
    chrono_by_day = {e["day"]: e for e in chrono_plan["entries"]}
    psprov_by_day = {e["day"]: e for e in psprov_plan["entries"]}

    invalid = [d for d in requested_days if d < 1 or d > max_day]
    if invalid:
        print(f"❌ Day(s) out of range (plan has {max_day} days): {invalid}")
        return 1

    chrono_out = REPO_ROOT / "audio" / "qt"
    psprov_out = REPO_ROOT / "audio" / "qt"
    chrono_out.mkdir(parents=True, exist_ok=True)
    psprov_out.mkdir(parents=True, exist_ok=True)
    generate_script = REPO_ROOT / "scripts" / "generate_plan_audio.py"

    bg_image = None
    if generate_mp4:
        bg_image = get_background_image()
        if not bg_image:
            print("⚠️  No background image found. Skipping MP4 generation.")
            print("   Place background.jpg or .png in assets/background/ to enable MP4.")
            generate_mp4 = False

    import os
    is_vps = "VPS_WEBHOOK_SECRET" in os.environ
    filename_lang = "ascii" if is_vps else "zh-tw"

    mode_label = "MP3 + MP4" if generate_mp4 else "MP3 only"
    print(f"\n🎧 Generating {len(requested_days)} day(s) [{mode_label}]")

    for day_num in requested_days:
        chrono_entry = chrono_by_day.get(day_num)
        psprov_entry = psprov_by_day.get(day_num)

        has_chrono = bool(chrono_entry and chrono_entry.get("chapters"))
        has_psprov = bool(psprov_entry and psprov_entry.get("chapters"))

        chrono_filename = None
        ch_zh = ch_en = None

        psprov_filename = None
        pp_zh = pp_en = None

        # ── 1) Chrono MP3 ────────────────────────────────────────────────
        if not has_chrono:
            print(f"⚠️  Day {day_num}: no chrono chapters, skipping chrono MP3.")
        else:
            chapters = chrono_entry["chapters"]
            ch_en = chapters_to_english(chapters)
            ch_zh = chapters_to_chinese(chapters, BOOK_CHINESE_TW)

            if is_vps:
                day_padded = f"{day_num:03d}" if chrono_plan["days"] >= 100 else f"{day_num:02d}"
                eng_ch_str = chapters_to_filename(chapters, abbr=BOOK_FILENAME_ABBR, between_groups="_")
                chrono_filename = f"{PLAN_ID}-day{day_padded}-{eng_ch_str}"
            else:
                ch_str = chapters_to_filename(chapters, abbr=BOOK_FILENAME_ABBR_ZH_TW, between_groups="-")
                chrono_filename = f"{chrono_plan['name_zh_tw']}第{day_num}天-{ch_str}"

            cmd = [
                sys.executable, str(generate_script),
                PLAN_ID,
                "-o", str(chrono_out),
                "--start-day", str(day_num),
                "--end-day", str(day_num),
                "--use-chapter-filename",
                "--no-speed-label",
                "--speed", "1.5",
                "--bgm", "--bgm-splits", "1",
                "--chapter-voice", "rotate",
                "--filename-lang", filename_lang,
            ]

            print(f"\n{'═' * 60}")
            print(f"Day {day_num}/186 — 半年歷史時序聆聽: {ch_zh}")
            print(f"  [{ch_en}]")
            print(f"{'═' * 60}")
            subprocess.run(cmd, check=True)
            print(f"✅ {chrono_filename}.mp3")

        # ── 2) Ps+Prov MP3 ───────────────────────────────────────────────
        if not has_psprov:
            print(f"⏭️  Day {day_num}: Ps+Prov skipped (Ps 119 day)")
        else:
            psprov_chapters = psprov_entry["chapters"]
            pp_en = chapters_to_english(psprov_chapters)
            pp_zh = chapters_to_chinese(psprov_chapters, BOOK_CHINESE_TW)

            if is_vps:
                day_padded = f"{day_num:03d}" if psprov_plan["days"] >= 100 else f"{day_num:02d}"
                eng_pp_str = chapters_to_filename(psprov_chapters, abbr=BOOK_FILENAME_ABBR, between_groups="_")
                psprov_filename = f"{PSPROV_PLAN_ID}-day{day_padded}-{eng_pp_str}"
            else:
                pp_str = chapters_to_filename(psprov_chapters, abbr=BOOK_FILENAME_ABBR_ZH_TW, between_groups="-")
                psprov_filename = f"{psprov_plan['name_zh_tw']}第{day_num}天-{pp_str}"

            cmd_pp = [
                sys.executable, str(generate_script),
                PSPROV_PLAN_ID,
                "-o", str(psprov_out),
                "--start-day", str(day_num),
                "--end-day", str(day_num),
                "--use-chapter-filename",
                "--no-speed-label",
                "--speed", "1.5",
                "--bgm", "--bgm-splits", "1",
                "--chapter-voice", "rotate",
                "--filename-lang", filename_lang,
            ]

            print(f"\nDay {day_num}/186 — 半年智慧讚美聆聽: {pp_zh}")
            print(f"  [{pp_en}]")
            subprocess.run(cmd_pp, check=True)
            print(f"✅ {psprov_filename}.mp3")

        # ── 3) MP4 Generation ────────────────────────────────────────────
        if generate_mp4:
            if has_chrono and chrono_filename:
                mp3_path = chrono_out / f"{chrono_filename}.mp3"
                if mp3_path.exists():
                    mp4_path = mp3_path.with_suffix(".mp4")
                    title = f"{chrono_plan['name_zh_tw']}第{day_num}天 — {ch_zh} ({ch_en})"
                    create_mp4(
                        str(mp3_path), str(mp4_path), bg_image,
                        title=title,
                        album=ALBUM_CHRONO,
                        track_num=day_num,
                    )
                else:
                    print(f"❌ MP3 not found for MP4: {mp3_path}")

            if has_psprov and psprov_filename:
                mp3_pp_path = psprov_out / f"{psprov_filename}.mp3"
                if mp3_pp_path.exists():
                    mp4_pp_path = mp3_pp_path.with_suffix(".mp4")
                    title_pp = f"{psprov_plan['name_zh_tw']}第{day_num}天 — {pp_zh} ({pp_en})"
                    create_mp4(
                        str(mp3_pp_path), str(mp4_pp_path), bg_image,
                        title=title_pp,
                        album=ALBUM_PSPROV,
                        track_num=day_num,
                    )
                else:
                    print(f"❌ MP3 not found for MP4: {mp3_pp_path}")

    print(f"\n{'═' * 60}")
    print(f"Done. {len(requested_days)} day(s) generated [{mode_label}].")
    print(f"  Output directory: {chrono_out}")
    print(f"{'═' * 60}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
